feat: HNM-0118: nav바에 흰색 배경 날린 로고로 변경하기
hanalum-dev/hanalum_web pull request #58
Opened 2021-03-24 02:57 UTC by Splanky0314

브렌치 feature/HNM-0118로 변경

2021-03-24 12:32 UTC, shinkeonkim commented on templates/nav.dj.html
> +                    <img src = "{% static 'img/no-title-logo-clearbackground.png'%}" height = "30"/>
no-title-logo로 파일명 넣어서 기존에 있던 파일들 다 날리고,
하나만 남깁시다.

2021-03-24 12:32 UTC, shinkeonkim requested changes

2021-03-24 12:32 UTC, shinkeonkim commented on templates/nav.dj.html
> +                    <img src = "{% static 'img/no-title-logo-clearbackground.png'%}" height = "30"/>
no-title-logo로 파일명 넣어서 기존에 있던 파일들 다 날리고,
하나만 남깁시다.

2021-03-24 12:57 UTC, Splanky0314 commented on templates/nav.dj.html
> +                    <img src = "{% static 'img/no-title-logo-clearbackground.png'%}" height = "30"/>
옛썰

2021-03-28 07:50 UTC, shinkeonkim approved these changes

2021-03-28 07:51 UTC, merged